name: Run tests

on:
  push:
    branches:
      - "**"
      # - "issue-**"
  # pull_request:
  #   branches: 
  #     - "dev"

jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "macos-latest", "windows-latest"]
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v2
      # - name: "Cache Conda"
      #   uses: actions/cache@v1
      #   with:
      #     path: /usr/share/miniconda/envs/portfolio_manager
      #     key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-conda-
      - name: "Setup Conda dependencies"
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: portfolio_manager
      - name: Conda info
        shell: bash -l {0}
        run: |
          conda list